### ISSUE TITLE
Undefined array key "cache"

### ISSUE THREAD

**Issue by bgeneto** [efipay/sdk-php-apis-efi#2]
After updating (via composer) to version 1.2.2 the following error is triggered in `vendor\efipay\sdk-php-apis-efi\src\Efi\ApiRequest.php(43)`:

```
Undefined array key "cache"
```

Making this version backward incompatible. Adding the line 

```
"cache" => false
```
to the options array seems to solve the issue. I think the `cache` key should have a default value or documented as required (also in examples).

**Comment by guilherme-cota-efi** [comment]
Hello, how are you?

We appreciate your contact and collaboration! We have fixed this issue in [version 1.2.3](https://github.com/efipay/sdk-php-apis-efi/tree/1.2.3).

Thanks!
