### ISSUE TITLE
Support symfony/cache v6

### ISSUE THREAD

**Issue by thiagoflessak** [efipay/sdk-php-apis-efi#3]
Hi,

Since version 1.1.0, symfony/cache (v5) became a dependency of this package.
This makes impossible to use the package when the application is already using packages from symfony v6.
Would it be possible to declare the dependency symfony/cache as v5 or v6?

`"symfony/cache": "^5.0 || ^6.0"`

**Comment by guilherme-cota-efi** [comment]
Hello, @thiagoflessak!

Of course. We've created [release 1.3.0](https://github.com/efipay/sdk-php-apis-efi/releases/tag/1.3.0), where it will be possible to use version 6.0 of symfony/cache.

Thank you very much for your contribution!
